const namesData = {
  "رضوان": {
    meaning: "اللہ کی رضا، خوشنودی",
    personality: "پرامن، اللہ کا پسندیدہ اور نرم دل شخص سمجھا جاتا ہے۔",
    background: "عربی نام ہے۔ جنت کے دروازے کے فرشتے کا نام بھی رضوان ہے۔",
    message: "اللہ کو راضی کرنے والے کام کریں، دنیا خود راضی ہو جائے گی۔"
  },
  "پرویز": {
    meaning: "فاتح، کامیاب، خوش قسمت",
    personality: "بہادر، محنتی اور لیڈر شپ والی شخصیت سمجھا جاتا ہے۔",
    background: "فارسی نام ہے۔ پرانے بادشاہوں کا لقب تھا۔",
    message: "محنت کبھی ضائع نہیں ہوتی، کامیابی آپ کا مقدر ہے۔"
  },
  "فیضان": {
    meaning: "فضل، کرم، برکت",
    personality: "سخی، مددگار اور نیک دل شخص سمجھا جاتا ہے۔",
    background: "عربی نام ہے جس کا مطلب ہے اللہ کا فضل اور فیض۔",
    message: "اپنے علم اور مال سے دوسروں کی خدمت کریں۔"
  },
  "میوش": {
    meaning: "زندگی، حیات",
    personality: "خوش مزاج، پرجوش اور سب کو ساتھ لے کر چلنے والی لڑکی سمجھی جاتی ہے۔",
    background: "فارسی/ترکی زبان کا جدید اور پیارا نام ہے۔",
    message: "اپنی مسکراہٹ سے دوسروں کی زندگی میں روشنی لائیں۔"
  },
  "شیر": {
    meaning: "بہادر، نڈر، جنگل کا بادشاہ",
    personality: "دلیر، وفادار اور حق کے لیے کھڑے ہونے والا شخص سمجھا جاتا ہے۔",
    background: "فارسی/اردو نام ہے جو بہادری کی علامت ہے۔",
    message: "ڈر کو شکست دیں اور حق کا ساتھ دیں۔"
  },
  "احمد": { meaning: "بہت تعریف کیا گیا", personality: "سچا، امانت دار", background: "حضور ﷺ کا مبارک نام", message: "اخلاق اچھا رکھیں" },
  "محمد": { meaning: "قابل تعریف", personality: "رہنما، رحم دل", background: "آخری نبی کا نام", message: "سنت پر عمل کریں" },
  "علی": { meaning: "بلند، عظمت والا", personality: "بہادر، انصاف پسند", background: "حضرت علیؓ کا نام", message: "علم حاصل کریں" },
  "حسن": { meaning: "خوبصورت، اچھا", personality: "پرکشش، نرم دل", background: "حضرت حسنؓ کا نام", message: "کردار خوبصورت بنائیں" },
  "حسین": { meaning: "بہت خوبصورت", personality: "بہادر، قربانی والا", background: "حضرت حسینؓ کا نام", message: "حق کے لیے کھڑے ہوں" },
  "بلال": { meaning: "پانی، تازگی", personality: "مؤذن، پابند", background: "حضرت بلالؓ کا نام", message: "نماز کی پابندی کریں" },
  "حمزہ": { meaning: "بہادر، شیر", personality: "نڈر، وفادار", background: "حضرت حمزہؓ کا نام", message: "حق کا ساتھ دیں" },
  "یوسف": { meaning: "اللہ اضافہ کرے", personality: "خوبصورت، صبر والا", background: "حضرت یوسفؑ کا نام", message: "صبر کا پھل میٹھا ہوتا ہے" },
  "ابراہیم": { meaning: "قوم کا باپ", personality: "دانا، اللہ کا دوست", background: "حضرت ابراہیمؑ کا نام", message: "توحید پر قائم رہیں" },
  "اسماعیل": { meaning: "اللہ نے سنا", personality: "فرمانبردار", background: "حضرت اسماعیلؑ کا نام", message: "والدین کا حکم مانیں" },
  "موسی": { meaning: "پانی سے نکالا گیا", personality: "کلیم اللہ، بہادر", background: "حضرت موسیؑ کا نام", message: "ظلم کے خلاف آواز اٹھائیں" },
  "عیسی": { meaning: "نجات دینے والا", personality: "رحم دل", background: "حضرت عیسیؑ کا نام", message: "محبت پھیلائیں" },
  "داؤد": { meaning: "محبوب", personality: "عادل، فنکار", background: "حضرت داؤدؑ کا نام", message: "انصاف کریں" },
  "سلیمان": { meaning: "پر امن", personality: "بادشاہ، حکمت والا", background: "حضرت سلیمانؑ کا نام", message: "عقل سے کام لیں" },
  "ایوب": { meaning: "رجوع کرنے والا", personality: "صبر کا پہاڑ", background: "حضرت ایوبؑ کا نام", message: "مشکل میں صبر کریں" },
  "خالد": { meaning: "ہمیشہ رہنے والا", personality: "بہادر جرنیل", background: "حضرت خالد بن ولید", message: "ہمت نہ ہاریں" },
  "طارق": { meaning: "رات کا ستارہ", personality: "فاتح", background: "طارق بن زیاد", message: "مشکل کو فتح کریں" },
  "عمر": { meaning: "زندگی، لمبی عمر", personality: "عادل، بہادر", background: "حضرت عمرؓ کا نام", message: "انصاف قائم کریں" },
  "عثمان": { meaning: "شیر کا بچہ", personality: "حیا دار، سخی", background: "حضرت عثمانؓ کا نام", message: "سخاوت کریں" },
  "طلحہ": { meaning: "درخت", personality: "بہادر صحابی", background: "حضرت طلحہؓ", message: "جان و مال قربان کریں" },
  "زبیر": { meaning: "مضبوط", personality: "بہادر", background: "حضرت زبیرؓ", message: "حق پر ڈٹ جائیں" },
  "سعد": { meaning: "خوش بختی", personality: "خوش قسمت", background: "حضرت سعدؓ", message: "شکر گزار رہیں" },
  "ارسلان": { meaning: "شیر", personality: "بہادر", background: "ترکی نام", message: "نڈر بنیں" },
  "دانش": { meaning: "علم، حکمت", personality: "عقل مند", background: "فارسی نام", message: "علم حاصل کریں" },
  "جاوید": { meaning: "ہمیشہ رہنے والا", personality: "وفادار", background: "فارسی نام", message: "وفا نبھائیں" },
  "عامر": { meaning: "آباد کرنے والا", personality: "تعمیراتی", background: "عربی نام", message: "ملک آباد کریں" },
  "فرحان": { meaning: "خوش ہونے والا", personality: "ہنس مکھ", background: "عربی نام", message: "خوشیاں بانٹیں" },
  "قاسم": { meaning: "تقسیم کرنے والا", personality: "انصاف پسند", background: "حضور کے بیٹے", message: "انصاف کریں" },
  "کامل": { meaning: "مکمل", personality: "باکردار", background: "عربی نام", message: "خود کو بہتر بنائیں" },
  "ماجد": { meaning: "بزرگ، عزت والا", personality: "عزت دار", background: "عربی نام", message: "عزت کمائیں" },
  "نوید": { meaning: "خوشخبری", personality: "خوش مزاج", background: "فارسی نام", message: "خوشخبری دیں" },
  "واجد": { meaning: "پانے والا", personality: "کامیاب", background: "عربی نام", message: "کوشش کرتے رہیں" },
  "ہارون": { meaning: "مددگار", personality: "وفادار", background: "حضرت ہارونؑ", message: "بھائی چارہ نبھائیں" },
  "یاسر": { meaning: "آسانی کرنے والا", personality: "آسان پسند", background: "حضرت یاسرؓ", message: "آسانیاں پیدا کریں" },
  "اذان": { meaning: "اعلان", personality: "پابند", background: "نماز کی پکار", message: "وقت کی پابندی کریں" },
  "انصر": { meaning: "مدد کرنے والا", personality: "مددگار", background: "عربی نام", message: "دوسروں کی مدد کریں" },
  "باسم": { meaning: "مسکرانے والا", personality: "خوش مزاج", background: "عربی نام", message: "مسکرا کر ملیں" },
  "ثاقب": { meaning: "چمکدار ستارہ", personality: "ذہین", background: "عربی نام", message: "علم کی روشنی پھیلائیں" },
  "حارث": { meaning: "کسان", personality: "محنتی", background: "عربی نام", message: "محنت سے کمائیں" },
  "رومان": { meaning: "بلند", personality: "پرکشش", background: "عربی نام", message: "کردار بلند رکھیں" },
  "ظفر": { meaning: "کامیابی", personality: "محنتی", background: "عربی نام", message: "کامیابی کے لیے لگیں" },
  "غفران": { meaning: "بخشش", personality: "معاف کرنے والا", background: "اللہ کی صفت", message: "معاف کرنا سیکھیں" },
  "لئیق": { meaning: "قابل", personality: "قابلیت والا", background: "عربی نام", message: "قابلیت بڑھائیں" },

  "فاطمہ": { meaning: "پاکیزہ", personality: "مہربان، باحیا", background: "حضرت فاطمہؓ کا نام", message: "حیا اختیار کریں" },
  "زینب": { meaning: "باپ کا زیور", personality: "بہادر، صبر والی", background: "حضرت زینبؓ کا نام", message: "ثابت قدم رہیں" },
  "خدیجہ": { meaning: "پہلے پیدا ہونے والی", personality: "تاجرہ، وفادار", background: "حضرت خدیجہؓ کا نام", message: "کاروبار میں سچائی" },
  "عائشہ": { meaning: "زندہ، خوشحال", personality: "ذہین، عالمہ", background: "حضرت عائشہؓ کا نام", message: "علم کی شمع جلائیں" },
  "حفصہ": { meaning: "شیر کا بچہ", personality: "بہادر، حافظہ", background: "حضرت حفصہؓ کا نام", message: "قرآن سے تعلق جوڑیں" },
  "مریم": { meaning: "عبادت گزار", personality: "پاکیزہ", background: "حضرت مریمؑ کا نام", message: "پاکدامنی اختیار کریں" },
  "آمنہ": { meaning: "پرامن", personality: "مہربان ماں", background: "حضور کی والدہ", message: "گھر کو جنت بنائیں" },
  "نور": { meaning: "روشنی", personality: "پر سکون", background: "اللہ کا نام", message: "دوسروں کے لیے روشنی بنیں" },
  "ایمان": { meaning: "یقین", personality: "مضبوط ایمان والی", background: "اسلام کی بنیاد", message: "ایمان مضبوط رکھیں" },
  "حنا": { meaning: "رحمت", personality: "نرم مزاج", background: "عربی نام", message: "محبت سے ملیں" },
  "ثناء": { meaning: "تعریف", personality: "شکر گزار", background: "اللہ کی تعریف", message: "ہر حال میں شکر کریں" },
  "دعا": { meaning: "التجا", personality: "عبادت گزار", background: "عبادت", message: "کثرت سے دعا کریں" },
  "رحمہ": { meaning: "رحمت", personality: "مہربان", background: "اللہ کی صفت", message: "رحم کرنا سیکھیں" },
  "سکینہ": { meaning: "دل کا سکون", personality: "با وقار", background: "قرآنی نام", message: "دل کو سکون دیں" },
  "طوبی": { meaning: "جنت کا درخت", personality: "نیک بخت", background: "جنت کا نام", message: "نیک اعمال کریں" },
  "ہاجرہ": { meaning: "ہجرت کرنے والی", personality: "صابرہ", background: "حضرت ہاجرہ", message: "اللہ پر توکل رکھیں" },
  "صفیہ": { meaning: "چنی ہوئی", personality: "دانا", background: "حضرت صفیہؓ", message: "دانائی سے فیصلہ کریں" },
  "جویریہ": { meaning: "نوجوان لڑکی", personality: "سخی", background: "حضرت جویریہؓ", message: "سخاوت کریں" },
  "بینش": { meaning: "بصیرت", personality: "دانا", background: "فارسی نام", message: "سمجھداری سے کام لیں" },
  "پری": { meaning: "فرشتہ", personality: "خوبصورت", background: "فارسی نام", message: "خوبصورتی کو سنواریں" },
  "حور": { meaning: "جنت کی لڑکی", personality: "پاکیزہ", background: "قرآنی نام", message: "پاکیزگی اختیار کریں" },
  "رابعہ": { meaning: "چوتھی", personality: "عابدہ", background: "حضرت رابعہ بصری", message: "عبادت کو ترجیح دیں" },
  "شمائل": { meaning: "خوبیاں", personality: "بااخلاق", background: "عربی نام", message: "اخلاق اچھے رکھیں" },
  "آسیہ": { meaning: "دلاسا دینے والی", personality: "صابرہ", background: "حضرت آسیہ", message: "ایمان پر ڈٹ جائیں" },
  "زلیخا": { meaning: "خوبصورت", personality: "نرم دل", background: "قرآنی کردار", message: "توبہ کی طاقت" },
  "سارہ": { meaning: "شہزادی", personality: "باوقار", background: "حضرت سارہ", message: "وقار سے رہیں" },
  "رقیہ": { meaning: "بلند", personality: "عبادت گزار", background: "حضرت رقیہؓ", message: "اللہ سے قرب مانگیں" },
  "ام کلثوم": { meaning: "گول چہرے والی", personality: "باحیا", background: "حضرت ام کلثومؓ", message: "صبر سے کام لیں" },
  "سمیہ": { meaning: "بلند", personality: "شہیدہ", background: "پہلی شہیدہ", message: "ایمان پر ڈٹ جائیں" },
  "نائلہ": { meaning: "کامیاب", personality: "محنتی", background: "عربی نام", message: "کامیابی کے لیے محنت کریں" },
  "اقراء": { meaning: "پڑھو", personality: "عالمہ", background: "پہلی وحی", message: "علم حاصل کریں" },
  "منزہ": { meaning: "پاکیزہ", personality: "باحیا", background: "عربی نام", message: "پاکیزگی اختیار کریں" },
  "مشال": { meaning: "مشعل، روشنی", personality: "رہنما", background: "عربی نام", message: "دوسروں کو راستہ دکھائیں" },
  "انعم": { meaning: "نعمت", personality: "شکر گزار", background: "عربی نام", message: "نعمتوں کا شکر کریں" },
  "اریبہ": { meaning: "ذہین", personality: "ذہین", background: "عربی نام", message: "عقل استعمال کریں" },
  "بشرہ": { meaning: "خوشخبری", personality: "خوش مزاج", background: "عربی نام", message: "خوشیاں بانٹیں" },
  "تبارک": { meaning: "بابرکت", personality: "بابرکت", background: "قرآنی نام", message: "برکت والا کام کریں" },
  "جنت": { meaning: "باغ", personality: "پر سکون", background: "جنت", message: "جنت والے اعمال کریں" },
  "حریم": { meaning: "حرمت والی", personality: "باحیا", background: "عربی نام", message: "حرمت کا خیال رکھیں" },
  "خصلت": { meaning: "عادت", personality: "بااخلاق", background: "عربی نام", message: "اچھی عادت اپنائیں" },
  "دانیہ": { meaning: "قریب", personality: "محبت کرنے والی", background: "عربی نام", message: "قریب رہیں" },
  "رابعہ": { meaning: "چوتھی", personality: "زاہدہ", background: "حضرت رابعہ", message: "زہد اختیار کریں" },
  "زہرہ": { meaning: "چمکدار", personality: "خوبصورت", background: "حضرت فاطمہ کا لقب", message: "روشنی پھیلائیں" },
  "سبا": { meaning: "صبح کی ہوا", personality: "نرم", background: "عربی نام", message: "نرمی اختیار کریں" },
  "شازیہ": { meaning: "شہزادی", personality: "نازک", background: "فارسی نام", message: "نازک مزاج بنیں" },
  "صائمہ": { meaning: "روزہ دار", personality: "عبادت گزار", background: "عربی نام", message: "روزہ رکھیں" },
  "طاہرہ": { meaning: "پاکیزہ", personality: "پاکیزہ", background: "عربی نام", message: "پاک رہیں" },
  "عالیہ": { meaning: "بلند", personality: "باہمت", background: "عربی نام", message: "ہمت بلند رکھیں" },
  "غزل": { meaning: "پیارا کلام", personality: "فنکارہ", background: "فارسی نام", message: "فن سے محبت کریں" },
  "فریحہ": { meaning: "خوش", personality: "ہنس مکھ", background: "عربی نام", message: "خوش رہیں" },
  "قمر": { meaning: "چاند", personality: "پرکشش", background: "عربی نام", message: "روشنی بنیں" },
  "لاریب": { meaning: "بے شک", personality: "سچی", background: "قرآنی نام", message: "سچ بولیں" },
  "مہناز": { meaning: "فخر", personality: "پر فخر", background: "فارسی نام", message: "فخر سے کام کریں" },
  "نرمين": { meaning: "نرم", personality: "نرم دل", background: "عربی نام", message: "نرمی اختیار کریں" },
  "وسیمہ": { meaning: "خوبصورت", personality: "خوبصورت", background: "عربی نام", message: "خوبصورتی کردار میں" },
  "ہما": { meaning: "خوش بختی کا پرندہ", personality: "خوش قسمت", background: "فارسی نام", message: "خوش بختی لائیں" },
  "یاسمین": { meaning: "خوشبودار پھول", personality: "خوشبودار", background: "عربی نام", message: "خوشبو پھیلائیں" }
};

const defaultData = {
  meaning: "اس بارے میں مزید معلومات جلد شامل کی جائیں گی۔",
  personality: "شخصیت انسان کے کردار اور اعمال سے بنتی ہے۔",
  background: "یہ نام موجودہ فہرست میں موجود نہیں تھا۔",
  message: "اچھا اخلاق اور مثبت سوچ کامیابی کی اصل بنیاد ہیں۔"
};
